plugins {
    id("spendlens.android.application")
    id("spendlens.android.hilt")
    alias(libs.plugins.kotlin.compose)
    // Consumes the profile generated by :benchmark and packages it into the APK.
    alias(libs.plugins.baselineprofile)
}

android {
    namespace = "com.spendlens"

    defaultConfig {
        applicationId = "com.spendlens"
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // The baseline profile plugin adds two build types of its own: `nonMinifiedRelease`, which it
    // profiles, and `benchmarkRelease`, which the benchmarks measure. Both are release compilation with
    // debug signing — a debug build would measure the debugger, since it disables ART optimisations.
    buildTypes {
        release {
            optimization {
                // R8 on: this is the build that ships. Everything below has been checked to survive it —
                // see proguard-rules.pro for the three libraries that needed help.
                enable = true
            }
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // Debug keys until Phase 6 adds a real keystore: without a signature the APK cannot be
            // installed, and a release build nobody has ever run is not a verified release build.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation(projects.core.common)
    implementation(projects.core.designsystem)
    implementation(projects.core.model)
    implementation(projects.feature.capture)
    implementation(projects.feature.expenses)
    implementation(projects.feature.insights)
    implementation(projects.feature.settings)
    implementation(projects.core.applock)

    // Installs the baseline profile that ships in the APK on first run.
    implementation(libs.androidx.profileinstaller)
    implementation(projects.sync)

    // The Application supplies WorkManager's configuration, with Hilt's worker factory.
    implementation(libs.androidx.work.runtime)
    implementation(libs.androidx.hilt.work)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    // App lock: foreground/background for the whole process, and lifecycle-aware state in the activity.
    implementation(libs.androidx.lifecycle.process)
    implementation(libs.androidx.lifecycle.runtime.compose)
    testImplementation(libs.junit)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
    debugImplementation(libs.androidx.compose.ui.tooling)

    baselineProfile(projects.benchmark)
}
